[package]
name = "dispatcher"
version = "0.0.1"
authors = ["wax911"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rumqttc = "0.0.4"